spring.application.name=asset-inventory-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/device_inventory_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.web=DEBUG
server.servlet.session.timeout=1h
